# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logsumexp <- function(x) {
    .Call(`_arcProbit_logsumexp`, x)
}

likAGH <- function(rho, list_eta, list_w, niter, ws, z) {
    .Call(`_arcProbit_likAGH`, rho, list_eta, list_w, niter, ws, z)
}

getEffects <- function(rho, list_eta, list_w, niter, ws, z) {
    .Call(`_arcProbit_getEffects`, rho, list_eta, list_w, niter, ws, z)
}

getEffectsOrd <- function(rho, alphae, list_eta, list_y, niter, ws, z) {
    .Call(`_arcProbit_getEffectsOrd`, rho, alphae, list_eta, list_y, niter, ws, z)
}

likAGHOrd <- function(rho, alphae, list_eta, list_y, niter, ws, z) {
    .Call(`_arcProbit_likAGHOrd`, rho, alphae, list_eta, list_y, niter, ws, z)
}

pmvnorm_cpp <- function(upper, rho, abseps = 1e-3) {
    .Call(`_arcProbit_pmvnorm_cpp`, upper, rho, abseps)
}

lik2_binary <- function(rho, etaG, list_ind, y) {
    .Call(`_arcProbit_lik2_binary`, rho, etaG, list_ind, y)
}

lik2_ord <- function(rho, tauG, etaG, list_ind, y) {
    .Call(`_arcProbit_lik2_ord`, rho, tauG, etaG, list_ind, y)
}

